# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: digitaldental_development
  username: jupita
  password: jupita123d
  host: localhost
  port: 5432


test:
  <<: *default
  database: digitaldental_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
